import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Nunito } from "@next/font/google";
import Head from "next/head";
import "./style.css";
import "../../lib/fontawesome-free/css/all.min.css";
import Script from "next/script";
import SideBar from "@/components/dashboard/sections/SideBar";
import TopBar from "@/components/dashboard/sections/TopBar";

const inter = Inter({ subsets: ["latin"] });
const nunito = Nunito({
  weight: ["400", "600", "900", "700"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${nunito.className} sidebar-toggled`}>
        <div id="wrapper">
          {/* Start of SideBar */}
          <SideBar />
          {/* End of SideBar */}

          <div id="content-wrapper" className="d-flex flex-column">
            <div id="content">
              {/* Start of TopBar */}
              <TopBar />
              {/* End of TopBar */}
              {children}
            </div>
            <footer
              className="sticky-footer  bg-gray-200 card shadow-sm p-2"
              style={{ position: "fixed", bottom: 0, width: "100%" }}
            >
              <div className="container my-auto">
                <div className="copyright text-center my-auto">
                  <span>Copyright &copy; Your Website 2021</span>
                </div>
              </div>
            </footer>
            <a className="scroll-to-top rounded" href="#page-top">
              <i className="fas fa-angle-up"></i>
            </a>
          </div>
        </div>

        {/* Load jQuery */}
        <Script
          src="/vendor/jquery/jquery.min.js"
          strategy="beforeInteractive"
        />

        {/* Load Bootstrap JS */}
        <Script
          src="/vendor/bootstrap/js/bootstrap.bundle.min.js"
          strategy="beforeInteractive"
        />

        {/* Core plugin JavaScript */}
        <Script
          src="/vendor/jquery-easing/jquery.easing.min.js"
          strategy="beforeInteractive"
        />

        {/* Custom scripts for all pages */}
        <Script src="/js/sb-admin-2.min.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
